name: FB Live Stream

on:
  workflow_dispatch:

jobs:
  start_stream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run Live Stream
        run: |
          ffmpeg -allowed_extensions ALL -re -user_agent "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Mobile Safari/537.36" -analyzeduration 15M -probesize 15M -i "https://edge2.roarzone.info:8447/roarzone/edge2/tsports/tracks-v1a1/mono.m3u8?token=fb049110385350bbd0940fea223144bdb6c3a3c9-2ff26de07d4c570fe74224b48411bfc5-1773418552-1773414952" -filter_complex "[0:v]crop=w=iw-10:h=ih-10:x=5:y=5,scale=800:450,eq=contrast=1.1:saturation=1.2:brightness=0.05,hue=h=5,unsharp=5:5:0.8:5:5:0.0,pad=854:580:27:65:color=black[v];[0:a]volume=0.5,asetrate=44100*1.05,atempo=0.95,highpass=f=200,lowpass=f=3000[a]" -map "[v]" -map "[a]" -bsf:v "filter_units=remove_types=6" -map_metadata -1 -r 24 -c:v libx264 -preset ultrafast -tune zerolatency -x264-params "nal-hrd=cbr:force-cfr=1:scenecut=0:bframes=0:no-cabac=1:aq-mode=3:aq-strength=1.5:me=dia:subme=0" -b:v 600k -maxrate 600k -bufsize 1200k -threads 8 -c:a aac -b:a 32k -ar 44100 -f flv -flvflags no_duration_filesize "rtmps://live-api-s.facebook.com:443/rtmp/FB-1186502920287276-0-Ab5Z3ga2WN8RM4hs1CvoYScD"
