name: Simple Telegram Stream

on:
  workflow_dispatch:

jobs:
  restream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Start Live Stream
        run: |
          ffmpeg -i "https://livecdn-bp-livestream.linewgen.xyz/stream/27/chunks.m3u8?x-sign=1d7965f7cc65b773c47bfdc2d8060c49&x-time=1773493260&is_vip=false&token=41cd7acbd67c8aca72a0be12dce98e37022d11a6" \
          -vf "scale=-2:720" \
          -c:v libx264 -preset veryfast -profile:v main -pix_fmt yuv420p -b:v 1500k -maxrate 1500k -bufsize 3000k \
          -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmps://dc5-1.rtmp.t.me/s/${{ secrets.TELEGRAM_STREAM_KEY }}"
