name: HDHub Telegram Link Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  scrape-link:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies & Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Run Scraper Script with Virtual Display
      run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python main.py
