name: Auto Update 1

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Unzip Protected Script
        run: unzip -P ${{ secrets.ZIP_PASSWORD2 }} run.zip

      - name: Run Python Script
        run: python run.py

      - name: Delete Script After Run
        if: always()
        run: rm -f run.py  # run.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api.json ALL.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update api.json and ALL.m3u"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write
