name: Generate BDIX M3U Playlist

on:
  schedule:
    - cron: '*/30 * * * *'  # প্রতি ৩০ মিনিটে রান করবে
  push:
    branches:
      - main
    paths:
      - '.github/workflows/bdix.yml'

jobs:
  generate_bdix_playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Scrape BDIX TV and Generate M3U
      run: |
        echo "#EXTM3U" > bdix.m3u

        python - <<EOF
        import requests
        from bs4 import BeautifulSoup

        url = "https://www.bdixtv24.xyz"
        headers = {
            "User-Agent": "Mozilla/5.0"
        }

        r = requests.get(url, headers=headers)
        soup = BeautifulSoup(r.text, "html.parser")

        iframes = soup.find_all("iframe")

        count = 1
        with open("bdix.m3u", "a", encoding="utf-8") as f:
            for iframe in iframes:
                src = iframe.get("src")
                if src and ("http" in src):
                    name = f"BDIX Channel {count}"
                    f.write(f'#EXTINF:-1 tvg-id="bdix{count}" group-title="BDIX TV", {name}\n')
                    f.write(f"{src}\n")
                    count += 1
        EOF

    - name: Configure Git
      run: |
        git config --global user.name "auto-update-bot"
        git config --global user.email "auto-update-bot@users.noreply.github.com"
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Commit and push if changed
      run: |
        git add bdix.m3u
        if git diff --cached --quiet; then
          echo "No changes in bdix.m3u"
        else
          git commit -m "Auto-generated: BDIX M3U playlist from bdixtv24.xyz"
          git push origin main
        fi
